// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeZJeb8_IbDZw3B62rl2jj6PT3hEAFSU',
    appId: '1:484664393889:web:d634f11b9785d43ce1b0e0',
    messagingSenderId: '484664393889',
    projectId: 'firstapp9788',
    authDomain: 'firstapp9788.firebaseapp.com',
    storageBucket: 'firstapp9788.firebasestorage.app',
    measurementId: 'G-1JT525K9S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYakkWroHBz7cmRxhvRf9vLbIRIh4d5AM',
    appId: '1:484664393889:android:f95fb74d13a2e5c9e1b0e0',
    messagingSenderId: '484664393889',
    projectId: 'firstapp9788',
    storageBucket: 'firstapp9788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeNRYSUrfh-a_AV7YHqmXq31RLmoVKL8A',
    appId: '1:484664393889:ios:d0f28eede630d426e1b0e0',
    messagingSenderId: '484664393889',
    projectId: 'firstapp9788',
    storageBucket: 'firstapp9788.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeNRYSUrfh-a_AV7YHqmXq31RLmoVKL8A',
    appId: '1:484664393889:ios:d0f28eede630d426e1b0e0',
    messagingSenderId: '484664393889',
    projectId: 'firstapp9788',
    storageBucket: 'firstapp9788.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzeZJeb8_IbDZw3B62rl2jj6PT3hEAFSU',
    appId: '1:484664393889:web:faf7d345848a847be1b0e0',
    messagingSenderId: '484664393889',
    projectId: 'firstapp9788',
    authDomain: 'firstapp9788.firebaseapp.com',
    storageBucket: 'firstapp9788.firebasestorage.app',
    measurementId: 'G-T20EGS2SXW',
  );
}
